<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net40</TargetFramework>
        <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
        
        <Version>1.0.0</Version>
        <FileVersion>1.0.0</FileVersion>
        <InformationalVersion>1.0.0</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"
                          Version="1.0.3"
                          PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="System.Windows.Forms" />
        <Reference Include="System.Drawing" />
    </ItemGroup>
</Project>